Repository samilaxy/ImageFX, pull requests merged in 2023-06, with the labels that each got.

#49 changed navigation routing to editpage
  Caching/Assets.xcassets/BlackFrame.imageset/BlackFrame.png
  Caching/Assets.xcassets/BlackFrame.imageset/Contents.json
  Caching/Assets.xcassets/DarkWoodFrame.imageset/Contents.json
  Caching/Assets.xcassets/DarkWoodFrame.imageset/DarkWoodFrame.png
  Caching/Assets.xcassets/GoldFrame.imageset/Contents.json
  Caching/Assets.xcassets/GoldFrame.imageset/GoldFrame.png
  Caching/Assets.xcassets/LightWoodFrame.imageset/Contents.json
  Caching/Assets.xcassets/LightWoodFrame.imageset/LightWoodFrame.png
  Views/ImageDetailView.swift
  Views/ImageEditView.swift
Labels: bug

#58 added frame
  Views/ImageEditView.swift
  Views/ImageGridView.swift
Labels: enhancement

#60 reduce transition speed
  Views/ImageEditView.swift
  Views/SavedImageView.swift
Labels: enhancement

#61 Feat/rotate image
  Views/SavedImageView.swift
Labels: enhancement

#62 Feat/rotate image
  Views/ImageDetailView.swift
  Views/ImageEditView.swift
  Views/ImageGridView.swift
Labels: enhancement

#63 updates
  Caching/Assets.xcassets/PopMenuColor.colorset/Contents.json
  Views/ImageDetailView.swift
  Views/ImageEditView.swift
  Views/SavedImageView.swift
  Views/SavedImagesView.swift
Labels: enhancement

#64 rotate image
  Utilities/ImageUtitlities.swift
  Views/ImageEditView.swift
  Views/SavedImageView.swift
Labels: enhancement

#66 reduce animation speed
  Utilities/ImageUtitlities.swift
  Views/ImageEditView.swift
Labels: enhancement

#72 Design achitecture
  Caching.xcodeproj/project.pbxproj
  Config.xcconfig
  Models/Models.swift
  Utilities/ImageUtitlities.swift
  View Models/ImageEditViewModel.swift
  View Models/ViewModel.swift
  Views/ImageDetailView.swift
  Views/ImageEditView.swift
  Views/ImageGridView.swift
  Views/SavedImageView.swift
  Views/SavedImagesView.swift
Labels: enhancement

#73 Revert 72 design achitecture
  Utilities/ImageUtitlities.swift
  Views/ImageEditView.swift
Labels: enhancement

#77 Bugs
  Caching.xcodeproj/project.pbxproj
  Caching/CachingApp.swift
  Caching/ContentView.swift
  Config.xcconfig
  View Models/ImageLoaderVM.swift
  View Models/ViewModel.swift
  Views/HomeView.swift
  Views/ImageDetailView.swift
  Views/ImageEditView.swift
  Views/ImageGridView.swift
  Views/ImageView.swift
Labels: enhancement

#78 Update HomeView.swift
  Views/HomeView.swift
Labels: enhancement

#79 Bugs
  Caching/CachingApp.swift
  View Models/ViewModel.swift
  Views/ImageDetailView.swift
Labels: bug

#80 blur issue
  Caching/ContentView.swift
  Config.xcconfig
  Utilities/ImageUtitlities.swift
  View Models/ImageEditViewModel.swift
  View Models/ImageLoaderVM.swift
  View Models/ViewModel.swift
  Views/HomeView.swift
  Views/ImageDetailView.swift
  Views/ImageEditView.swift
  Views/ImageView.swift
  Views/SavedImagesView.swift
Labels: enhancement

#81 blur not affecting frame
  Caching.xcodeproj/project.pbxproj
  ImageData.xcdatamodeld/ImageData.xcdatamodel/contents
  Utilities/ImageUtitlities.swift
  View Models/ImageEditViewModel.swift
  View Models/ViewModel.swift
  Views/HomeView.swift
  Views/ImageData+CoreDataClass.swift
  Views/ImageData+CoreDataProperties.swift
  Views/ImageDetailView.swift
  Views/ImageEditView.swift
  Views/SavedImagesView.swift
Labels: enhancement

#83 Favorite image
  Views/HomeView.swift
Labels: enhancement

#85 favorite on details page
  Views/HomeView.swift
  Views/ImageDetailView.swift
  Views/SavedImageView.swift
Labels: enhancement

#87 options after edit
  Views/HomeView.swift
  Views/ImageDetailView.swift
  Views/ImageEditView.swift
  Views/SavedImagesView.swift
Labels: documentation, enhancement

#90 bug: blur changes rotation
  Config.xcconfig
  Utilities/ImageUtitlities.swift
  View Models/ImageEditViewModel.swift
  View Models/ViewModel.swift
  Views/HomeView.swift
  Views/ImageDetailView.swift
Labels: bug, enhancement
